export interface QpaTemplateItem {
  itemNo: number
  category: string
  subCategory: string
  isKey: boolean
  checkItem: string
  criteria: string
  potential: number
}

export const QPA_TEMPLATE: QpaTemplateItem[] = [
  // ─── 1. 품질 경영 ───────────────────────────────────────────
  {
    itemNo: 1,
    category: "1. 품질 경영",
    subCategory: "1.1 품질경영 일반",
    isKey: false,
    checkItem: "품질경영시스템 인증을 유지하고 있는가?",
    criteria: "4점 : 유효한 시스템 인증서를 보유하고 있음\n0점 : 유효한 시스템 인증서가 없음",
    potential: 4,
  },
  {
    itemNo: 2,
    category: "1. 품질 경영",
    subCategory: "1.1 품질경영 일반",
    isKey: false,
    checkItem: "품질경영시스템에 대한 내부심사를 실시하는가?",
    criteria: "2점 : 내부심사원을 보유하고 정해진 주기에 따라 내부심사 및 시정조치 실시\n0점 : 내부심사 미실시",
    potential: 2,
  },
  {
    itemNo: 3,
    category: "1. 품질 경영",
    subCategory: "1.1 품질경영 일반",
    isKey: false,
    checkItem: "경영검토는 주기적으로 실시되고 있는가?",
    criteria: "2점 : ISO 요구사항에 따라 경영 검토가 주기적으로 실시됨\n0점 : 경영검토가 주기적으로 실시되지 않음",
    potential: 2,
  },
  {
    itemNo: 4,
    category: "1. 품질 경영",
    subCategory: "1.2 품질 조직",
    isKey: false,
    checkItem: "품질관리를 위한 조직이 별도로 구성되어 있는가?",
    criteria: "2점 : 품질 조직이 구성되어 있으며, 별도 인원 운영 중\n1점 : 품질 조직이 구성되어 있으나, 다른 업무와 겸직 중\n0점 : 품질 조직이 구성되어 있지 않음",
    potential: 2,
  },
  {
    itemNo: 5,
    category: "1. 품질 경영",
    subCategory: "1.3 변경(PPAP/4M) 관리 기준",
    isKey: false,
    checkItem: "4M 변경을 위한 업무절차가 있는가?",
    criteria: "2점 : 설계, 4M 변경 이력관리 양호하며, 초기유동 관리 상태 양호함\n1점 : 업무절차 수립중이며, 내부 및 고객승인 이력 관리상태 양호함\n0점 : 설계, 4M 변경처리 업무절차 문서화 미흡 / 변경이력 관리 안됨",
    potential: 2,
  },
  {
    itemNo: 6,
    category: "1. 품질 경영",
    subCategory: "1.4 3정 5S 상태",
    isKey: false,
    checkItem: "제조공장, 공정의 전반적인 3정 5S 상태는 적절한가?",
    criteria: "4점 : 매우 우수\n3점 : 우수\n2점 : 양호\n1점 : 미흡",
    potential: 4,
  },
  {
    itemNo: 7,
    category: "1. 품질 경영",
    subCategory: "1.4 3정 5S 상태",
    isKey: false,
    checkItem: "작업장을 항상 최상의 상태로 유지하고 있는가?",
    criteria: "4점 : 업무 절차 및 실행계획이 있으며 정기적인 3정5S 실시 중\n3점 : 업무 절차 및 실행계획은 있으나 비정기적인 3정5S 실시 중\n1점 : 업무 절차 및 실행계획은 있으나 미실시됨\n0점 : 업무 절차 및 실행 계획 없음",
    potential: 4,
  },
  // ─── 2. 외주품/원자재 관리 ──────────────────────────────────
  {
    itemNo: 8,
    category: "2. 외주품/원자재 관리",
    subCategory: "2.1 수입검사",
    isKey: false,
    checkItem: "원자재 (도체, 컴파운드) 에 대한 규격을 보유하고 있는가?",
    criteria: "3점 : 원자재규격(또는 외주사양서) 을 보유하고 있으며, 내용이 충실함\n2점 : 원자재규격(또는 외주사양서) 을 보유하고 있으나, 내용이 일부 미흡함\n1점 : 원자재규격(또는 외주사양서) 을 일부 보유하고 있지 않음\n0점 : 원자재규격(또는 외주사양서) 가 없음",
    potential: 3,
  },
  {
    itemNo: 9,
    category: "2. 외주품/원자재 관리",
    subCategory: "2.1 수입검사",
    isKey: false,
    checkItem: "수입검사는 기준에 의해 실시되고 결과는 기록관리 되는가?",
    criteria: "3점 : 수입검사 기준에 따라 수입검사 실시하고 결과 기록 양호(관리자 승인)\n2점 : 수입검사 기준이 일부 미흡하나, 수입검사 실시하고 결과 기록\n1점 : 별도 수입검사를 실시하지 않고 성적서 Review 만 실시\n0점 : 수입검사 결과 없고, 시험성적서도 보관하지 않음",
    potential: 3,
  },
  {
    itemNo: 10,
    category: "2. 외주품/원자재 관리",
    subCategory: "2.1 수입검사",
    isKey: false,
    checkItem: "수입검사 부적합품은 정확히 격리되는가?",
    criteria: "3점 : 격리 공간/방법 등이 명확하여 양품과 혼입되지 않음\n2점 : 격리 공간이 불명확하나, 격리 방법이 명확하여 양품과 혼입되지 않음\n1점 : 격리 공간/방법이 불명확하여 양품과 혼입 가능성 있음\n0점 : 부적합품 격리 미실시",
    potential: 3,
  },
  {
    itemNo: 11,
    category: "2. 외주품/원자재 관리",
    subCategory: "2.1 수입검사",
    isKey: false,
    checkItem: "수입검사 부적합은 절차에 따라 보고/조치/관리 되는가?",
    criteria: "3점 : NCR 발행 및 개선조치 실시\n2점 : NCR은 발행하고 있으나, 개선 조치 미실시\n1점 : 부적합 처리 절차는 있으나 NCR 미발행\n0점 : 부적합 처리 절차가 없음",
    potential: 3,
  },
  {
    itemNo: 12,
    category: "2. 외주품/원자재 관리",
    subCategory: "2.2 협력사 관리",
    isKey: false,
    checkItem: "협력업체에 대한 정기적인 공정감사를 진행 하였는가?",
    criteria: "3점 : 협력업체 평가 기준이 있고, 정기적인 공정감사 실시\n2점 : 협력업체 평가 기준은 없으나, 정기적인 공정감사 실시\n1점 : 공정감사를 실시하고 있으나, 일부 업체가 누락됨\n0점 : 협력업체 공정감사 미실시",
    potential: 3,
  },
  // ─── 3. 생산공정 관리 ───────────────────────────────────────
  {
    itemNo: 13,
    category: "3. 생산공정 관리",
    subCategory: "3.1 작업표준",
    isKey: false,
    checkItem: "모든 공정의 작업표준서가 최신본으로 관리되고 있는가?",
    criteria: "4점 : 모든 공정 작업표준서가 최신본으로 작성되고 관리자 승인 완료\n3점 : 작업표준서 일부가 최신본으로 관리되지 않음\n2점 : 중요 공정의 작업표준서 일부가 없거나 최신본으로 작성되지 않음\n1점 : 중요 공정을 포함한 대부분의 작업표준서가 없거나 최신본으로 작성되지 않음\n0점 : 작업표준서가 없음",
    potential: 4,
  },
  {
    itemNo: 14,
    category: "3. 생산공정 관리",
    subCategory: "3.1 작업표준",
    isKey: false,
    checkItem: "작업표준서는 작업자가 쉽게 확인 가능한 위치에 있는가?",
    criteria: "4점 : 작업중에도 별도 행위없이 육안으로 확인 가능함\n3점 : 공정내 비치되어 있으나 확인을 위해서는 별도 행위가 필요함\n2점 : 공정 주변에 있으나, 확인을 위해서 이동이 필요함\n1점 : 공정 외부에 있음 (사무실 보관 등)\n0점 : 작업표준서가 없음",
    potential: 4,
  },
  {
    itemNo: 15,
    category: "3. 생산공정 관리",
    subCategory: "3.1 작업표준",
    isKey: false,
    checkItem: "작업표준서에 따라 작업자가 작업/검사를 이행하는가?",
    criteria: "4점 : 작업표준서와 실제 작업/검사 일치\n3점 : 작업표준서와 실제 작업/검사 불일치가 1건이 발견됨\n2점 : 작업표준서와 실제 작업/검사 불일치가 2 ~ 4건이 발견됨\n1점 : 작업표준서와 실제 작업/검사 불일치가 5건 이상이 발견됨",
    potential: 4,
  },
  {
    itemNo: 16,
    category: "3. 생산공정 관리",
    subCategory: "3.1 작업표준",
    isKey: false,
    checkItem: "외국인 작업자를 위한 작업표준서가 준비되어 있는가? (서류·동영상·사진 등 / 외국인 작업자 없을 시 N/A 채점)",
    criteria: "4점 : 외국인 작업자가 쉽게 이해할 수 있음\n2점 : 외국인 작업자가 혼자 이해하기 어려움 (관리자 지원 필요)\n0점 : 외국인 작업자를 위한 작업표준서가 준비 안됨",
    potential: 4,
  },
  {
    itemNo: 17,
    category: "3. 생산공정 관리",
    subCategory: "3.2 작업일지",
    isKey: false,
    checkItem: "모든 공정의 작업일지가 실시간으로 작성되는가?",
    criteria: "4점 : 작업일지가 작업표준의 내용에 맞게 작성됨 (점검한 모든 공정)\n3점 : 작업일지가 작업표준에 내용에 맞게 작성되나, 일부 내용의 누락 존재\n2점 : 일부 공정 작업일지 작성이 누락됨\n0점 : 작업일지가 없음",
    potential: 4,
  },
  {
    itemNo: 18,
    category: "3. 생산공정 관리",
    subCategory: "3.2 작업일지",
    isKey: false,
    checkItem: "작업일지는 보관되어 있는가?",
    criteria: "3점 : 3년이상 찾기 쉽게 보관됨\n2점 : 1년이상 3년미만 찾기 쉽게 보관됨\n1점 : 1년미만 보관하며 찾기가 어려움\n0점 : 보관되어 있지 않음",
    potential: 3,
  },
  {
    itemNo: 19,
    category: "3. 생산공정 관리",
    subCategory: "3.2 작업일지",
    isKey: false,
    checkItem: "공정 자주검사 결과는 작성되는가?",
    criteria: "4점 : 자주검사 결과가 기준에 맞게 작성됨 (점검한 모든 공정)\n3점 : 자주검사 결과가 기준에 맞게 작성되나, 일부 항목 누락 존재\n2점 : 일부 공정 자주검사 작성이 누락됨\n0점 : 공정 자주검사 결과가 없음",
    potential: 4,
  },
  {
    itemNo: 20,
    category: "3. 생산공정 관리",
    subCategory: "3.2 작업일지",
    isKey: false,
    checkItem: "원자재 규격, 로트번호는 기록되는가?",
    criteria: "4점 : 모든 원자재 규격, 로트번호가 기록됨\n2점 : 일부 원자재 규격, 로트번호가 기록됨\n0점 : 원자재 로트번호가 기록되지 않음",
    potential: 4,
  },
  {
    itemNo: 21,
    category: "3. 생산공정 관리",
    subCategory: "3.3 F/Proof 관리",
    isKey: false,
    checkItem: "제조공정에서 불량(외경, 혹, 스파크 등)을 예방/검출 하는가?",
    criteria: "4점 : F/Proof 장비(외경, 혹, 스파크 등) 를 통해 불량 예방됨\n2점 : F/Proof 장비(외경, 혹, 스파크 등) 를 통해 일부 불량 예방됨\n0점 : F/Proof 장비가 없으며, 생산공정에서 자동으로 예방/검출되지 않음",
    potential: 4,
  },
  {
    itemNo: 22,
    category: "3. 생산공정 관리",
    subCategory: "3.3 F/Proof 관리",
    isKey: false,
    checkItem: "F/Proof 설비 검출력에 대하여 정기적으로 체크하는가?",
    criteria: "4점 : 검교정 (대상일 경우) 진행하고, 1회/분기 정기 체크함\n3점 : 검교정 (대상일 경우) 진행하고, 1회/반기 정기 체크함\n2점 : 검교정 (대상일 경우) 진행하고, 1회/년 정기 체크함\n1점 : 검교정 진행 없이, 1회/년 정기 체크함\n0점 : 정기적인 체크 기록이 없음",
    potential: 4,
  },
  {
    itemNo: 23,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "제조설비의 번호는 있는가?",
    criteria: "2점 : 제조설비 번호가 부여되어 있고, 팻말이 부착되어 있음\n1점 : 제조설비 번호는 부여되어 있으나, 팻말이 없음 (ERP 혹은 별도파일에 설비번호 부여)\n0점 : 제조설비 번호가 부여되어 있지 않음",
    potential: 2,
  },
  {
    itemNo: 24,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "다이/니플은 정리정돈 되어 있고, 청결한 상태를 유지하는가? (다이/니플이 없는 공정의 경우 N/A 채점)",
    criteria: "2점 : 보관함에 정돈 및 Size 식별이 되어 있고, 전체가 청결한 상태를 유지함\n1점 : 보관함에 정돈 및 Size 식별 관리가 미흡함\n0점 : 보관함이 없고, 청결하지 않음",
    potential: 2,
  },
  {
    itemNo: 25,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "설비 정기점검 계획은 있는가?",
    criteria: "2점 : 설비 정기점검 계획이 있으며, 점검실적이 일치함\n1점 : 설비 정기점검 계획 및 점검실적이 미흡함\n0점 : 설비 정기점검 계획과 실적이 없음",
    potential: 2,
  },
  {
    itemNo: 26,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "설비 일상점검은 하는가?",
    criteria: "2점 : 일상점검 체크시트가 있고, 일상점검을 함\n1점 : 일상점검 체크시트가 있고, 일상점검이 일부 누락됨\n0점 : 일상점검 체크시트가 없고, 일상점검을 하지 않음",
    potential: 2,
  },
  {
    itemNo: 27,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "설비 보전활동 (고장이력, 수리내용 등) 기록되는가?",
    criteria: "2점 : 설비 보전활동 (고장내용, 수리내용) 기록관리 되고 있음\n0점 : 설비 보전활동 (고장내용, 수리내용) 기록이 없음",
    potential: 2,
  },
  {
    itemNo: 28,
    category: "3. 생산공정 관리",
    subCategory: "3.4 설비/TOOL 관리",
    isKey: false,
    checkItem: "소모품 교체 주기 및 교체 이력을 관리하는가?",
    criteria: "2점 : 소모품 교체주기가 설정되어 있고, 교체이력이 관리됨\n1점 : 소모품 교체주기가 있으나, 교체이력이 없음\n0점 : 소모품 교체주기도 없고, 교체이력도 없음",
    potential: 2,
  },
  {
    itemNo: 29,
    category: "3. 생산공정 관리",
    subCategory: "3.5 작업자 교육",
    isKey: false,
    checkItem: "작업자에 대한 자격 인증제를 실시하는가?",
    criteria: "2점 : 자격 인증제를 실시하고 있고 인증 요건이 객관적임\n1점 : 자격 인증제를 실시하고 있고 인증 요건 미흡 (근속년수, 주관적 판단 등)\n0점 : 자격 인증제 미실시",
    potential: 2,
  },
  {
    itemNo: 30,
    category: "3. 생산공정 관리",
    subCategory: "3.5 작업자 교육",
    isKey: false,
    checkItem: "신규 작업자에 대한 교육 프로그램이 실효성 있게 수립되었는가?",
    criteria: "2점 : 교육 프로그램이 있고, 그에 따라 교육이 실시되고 있음\n1점 : 교육 프로그램이 있으나, 교육 이력이 미흡함\n0점 : 교육 프로그램 없음",
    potential: 2,
  },
  // ─── 4. 검사/시험 관리 ──────────────────────────────────────
  {
    itemNo: 31,
    category: "4. 검사/시험 관리",
    subCategory: "4.1 제품검사",
    isKey: false,
    checkItem: "완제품검사를 위한 규격 (외주사양서, 재료규격)은 최신본을 보유하고 있는가?",
    criteria: "3점 : 제품규격(외주사양서 또는 재료규격)을 보유하고 있으며, 이력 관리 실시\n2점 : 제품규격(외주사양서 또는 재료규격)을 보유하고 있으나, 이력관리 미흡\n1점 : 제품규격(외주사양서 또는 재료규격)을 보유하고 있으나, 보관 관리 상태 미흡함\n0점 : 제품규격(외주사양서 또는 재료규격)을 보유하지 않음",
    potential: 3,
  },
  {
    itemNo: 32,
    category: "4. 검사/시험 관리",
    subCategory: "4.1 제품검사",
    isKey: false,
    checkItem: "완제품검사 구역의 레이아웃은 명확한가? (검사대기/검사완료, 표지판, 팔렛트/박스 등)",
    criteria: "3점 : 완제품검사 장소가 별도로 존재하며, 레이아웃의 구분이 명확함\n2점 : 완제품검사 장소가 별도로 존재하나, 레이아웃이 부정확함\n1점 : 완제품검사 장소가 별도로 존재하지 않으나, 다른 작업과 병행하여 사용함\n0점 : 완제품검사 장소가 없음",
    potential: 3,
  },
  {
    itemNo: 33,
    category: "4. 검사/시험 관리",
    subCategory: "4.1 제품검사",
    isKey: false,
    checkItem: "완제품검사는 기준에 의해 실시되고 결과는 기록관리 되는가?",
    criteria: "3점 : 완제품검사 결과 기록하여 보관하며 관리자 승인됨 (전산시스템/수기 작성 등)\n2점 : 완제품검사 결과 기록하여 보관하나, 관리자 미승인\n1점 : 완제품검사 결과 기록 일부 누락\n0점 : 완제품검사 결과 없음",
    potential: 3,
  },
  {
    itemNo: 34,
    category: "4. 검사/시험 관리",
    subCategory: "4.1 제품검사",
    isKey: false,
    checkItem: "고객 제출용 검사성적서 (또는 QMS) 는 작성하여 제출하는가?",
    criteria: "2점 : 검사성적서를 작성하여 제출함\n0점 : 검사성적서 미 제출",
    potential: 2,
  },
  {
    itemNo: 35,
    category: "4. 검사/시험 관리",
    subCategory: "4.2 계측기 관리",
    isKey: false,
    checkItem: "계측기 리스트를 관리하는가?",
    criteria: "2점 : 계측기 리스트 관리함\n0점 : 계측기 리스트 관리하지 않음",
    potential: 2,
  },
  {
    itemNo: 36,
    category: "4. 검사/시험 관리",
    subCategory: "4.2 계측기 관리",
    isKey: false,
    checkItem: "제품검사를 위한 계측기를 보유하고 있는가?",
    criteria: "2점 : 모든 계측기를 보유하고 있음 (외부 시험기관과의 용역 계약 시 보유로 인정)\n1점 : 일부 계측기를 보유하고 있음\n0점 : 계측기를 보유하고 있지 않음",
    potential: 2,
  },
  {
    itemNo: 37,
    category: "4. 검사/시험 관리",
    subCategory: "4.2 계측기 관리",
    isKey: false,
    checkItem: "외부 공인시험기관으로부터 정기 검교정을 실시하는가?",
    criteria: "2점 : 모든 계측기의 검교정을 실시\n1점 : 일부 계측기의 검교정을 실시, 일부는 미 실시\n0점 : 계측기의 검교정이 되지 않음",
    potential: 2,
  },
  {
    itemNo: 38,
    category: "4. 검사/시험 관리",
    subCategory: "4.3 부적합 관리",
    isKey: false,
    checkItem: "부적합품은 정확히 격리되는가?",
    criteria: "3점 : 격리 공간/방법 등이 명확하여 양품과 혼입되지 않음\n2점 : 격리 공간이 불명확하나, 격리 방법이 명확하여 양품과 혼입되지 않음\n1점 : 격리 공간/방법이 불명확하여 양품과 혼입 가능성 있음\n0점 : 부적합품 격리 미실시",
    potential: 3,
  },
  {
    itemNo: 39,
    category: "4. 검사/시험 관리",
    subCategory: "4.3 부적합 관리",
    isKey: false,
    checkItem: "부적합품 처리 이력을 기록 관리 하는가?",
    criteria: "3점 : 조치 이력이 최근까지 누락없이 관리됨 (2년 이상)\n2점 : 조치 이력이 일부 누락\n1점 : 조치 이력이 대부분 누락\n0점 : 조치 이력 관리 미실시",
    potential: 3,
  },
  {
    itemNo: 40,
    category: "4. 검사/시험 관리",
    subCategory: "4.3 부적합 관리",
    isKey: false,
    checkItem: "부적합에 대한 원인 및 개선활동을 하는가?",
    criteria: "3점 : 원인분석 및 개선활동을 수행하며, 대책서 작성 능력이 우수함\n2점 : 원인분석 및 개선활동을 수행하나, 대책서 작성 수준이 보통임\n1점 : 원인분석 및 개선활동을 수행하나, 대책서 작성 수준이 미흡함\n0점 : 원인분석 및 개선활동 및 대책서 작성이 어려움",
    potential: 3,
  },
  {
    itemNo: 41,
    category: "4. 검사/시험 관리",
    subCategory: "4.4 검사원 인증 관리",
    isKey: false,
    checkItem: "검사원에 대한 자격 인증제를 실시하는가?",
    criteria: "2점 : 자격 인증제를 실시하고 있고 인증 요건이 객관적임\n1점 : 자격 인증제를 실시하고 있고 인증 요건 미흡 (근속년수, 주관적 판단 등)\n0점 : 자격 인증제 미실시",
    potential: 2,
  },
  {
    itemNo: 42,
    category: "4. 검사/시험 관리",
    subCategory: "4.4 검사원 인증 관리",
    isKey: false,
    checkItem: "신규 검사원에 대한 교육 프로그램이 실효성 있게 수립되었는가? (검사원이 없을 경우 N/A 채점)",
    criteria: "2점 : 교육 프로그램이 있고, 그에 따라 교육이 실시되고 있음\n1점 : 교육 프로그램이 있으나, 교육 이력이 미흡함\n0점 : 교육 프로그램 없음",
    potential: 2,
  },
  // ─── 5. 물류/재고 관리 ──────────────────────────────────────
  {
    itemNo: 43,
    category: "5. 물류/재고 관리",
    subCategory: "5.1 로트 추적성 관리",
    isKey: false,
    checkItem: "공정이동간 반/완제품 식별을 위한 공정이동표 (꼬리표) 관리가 적절하게 되는가?",
    criteria: "4점 : 공정이동표가 부착되고, 내용 (공정, 품명, 날짜, 조장 등) 이 충분함\n2점 : 공정이동표가 부착되고 있으나, 내용 (공정, 품명, 날짜, 조장 등) 이 미흡함\n0점 : 공정이동표가 부착되지 않음",
    potential: 4,
  },
  {
    itemNo: 44,
    category: "5. 물류/재고 관리",
    subCategory: "5.1 로트 추적성 관리",
    isKey: true,
    checkItem: "완제품에서 자작/외주공정을 거쳐 원재료까지 추적이 되는가?",
    criteria: "4점 : 원자재, 외주공정 전체 로트추적 가능함\n2점 : 원자재, 외주공정 중 일부 로트추적 안됨\n0점 : 로트추적 안됨",
    potential: 4,
  },
  {
    itemNo: 45,
    category: "5. 물류/재고 관리",
    subCategory: "5.2 재고관리",
    isKey: false,
    checkItem: "원재료/외주품/부자재/완제품의 특성에 맞는 보관 기준이 수립되어 있는가?",
    criteria: "3점 : 보관 기준 명확하며, 해당 기준에 따라 실행함\n2점 : 보관 기준 명확하나 보관 상태가 일부 미흡함\n1점 : 보관 기준이 미흡하며, 보관 상태가 미흡함\n0점 : 보관 기준이 없고, 보관 상태가 미흡함",
    potential: 3,
  },
  {
    itemNo: 46,
    category: "5. 물류/재고 관리",
    subCategory: "5.2 재고관리",
    isKey: false,
    checkItem: "원재료/외주품/부자재/완제품의 장기/불용 재고에 대한 관리 절차가 수립이 되어 있는가?",
    criteria: "3점 : 장기/불용 재고 관리 기준이 명확하며, 해당 기준에 따라 실행함\n2점 : 장기/불용 재고 관리 기준이 명확하나, 일부 관리 상태가 미흡함\n1점 : 장기/불용 재고 관리 기준이 미흡하며, 관리 상태가 미흡함\n0점 : 장기/불용 재고 관리 기준이 없고, 관리 상태가 미흡함",
    potential: 3,
  },
  {
    itemNo: 47,
    category: "5. 물류/재고 관리",
    subCategory: "5.2 재고관리",
    isKey: false,
    checkItem: "원재료/외주품/부자재/완제품의 재고는 선입선출이 될 수 있도록 시스템이 구축되어 있는가?",
    criteria: "4점 : 전산시스템을 통한 선입선출 적용\n3점 : 전산시스템은 없으나, 선입선출 방안 구축되어 있으며 관리 양호함\n2점 : 전산시스템은 없으나, 선입선출 방안 구축되어 있으며 관리 일부 미흡함\n1점 : 전산시스템은 없으나, 선입선출 방안 구축되어 있으며 관리 대부분 미흡함\n0점 : 선입선출 방안 미 구축",
    potential: 4,
  },
]

export const QPA_CATEGORIES = [
  { name: "1. 품질 경영", potential: 20 },
  { name: "2. 외주품/원자재 관리", potential: 15 },
  { name: "3. 생산공정 관리", potential: 55 },
  { name: "4. 검사/시험 관리", potential: 30 },
  { name: "5. 물류/재고 관리", potential: 18 },
] as const

export const QPA_TOTAL_POTENTIAL = 138

export function calcQpaScores(items: { potential: number; score: number; isNA: boolean }[]) {
  const effectivePotential = items.reduce((s, i) => s + (i.isNA ? 0 : i.potential), 0)
  const totalScore = items.reduce((s, i) => s + (i.isNA ? 0 : i.score), 0)
  const totalPercent = effectivePotential > 0 ? Math.round((totalScore / effectivePotential) * 1000) / 10 : 0
  const level = totalPercent >= 90 ? "A" : totalPercent >= 80 ? "B" : totalPercent >= 70 ? "C" : "D"
  const result: "PASS" | "FAIL" | "TBD" = effectivePotential === 0 ? "TBD" : totalPercent >= 70 ? "PASS" : "FAIL"
  return { effectivePotential, totalScore, totalPercent, level, result }
}
